baseurl = "https://www.josselingiffard.fr"
title = "josselin giffard-carlet"
theme = "hugo-coder"
languagecode = "fr"
defaultcontentlanguage = "fr"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Josselin GIFFARD-CARLET"
  license = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA-4.0</a>'
  info = "Géomaticien"
  description = "Je suis ingénieur, géomaticien et développeur web. Sur ce blog personnel dédié à la géomatique, j'exploite des données spatialisées ouvertes, les appliquant à des cas pratiques à l'aide de logiciels ou de langages de programmation. Mon objectif est de partager l'expérimentation et les connaissances que j'en tire à travers des articles de type tutoriels."
  keywords = "geomatic, cartography, satellite imagery, blog, engineer, developer"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  # Git Commit in Footer
  commit = "https://github.com/luizdepra/hugo-coder/tree/"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[markup.goldmark.renderer]
  unsafe = true

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Redcozmo/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/jgiffardcarlet"
[[params.social]]
  name = "linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/josselin-giffard-carlet/"

# Menu links
[[menu.main]]
  name = "Articles"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Notes"
  weight = 2
  url  = "notes/"
[[menu.main]]
  name = "À propos"
  weight = 3
  url = "about/"
