---
title: "Utilisation des données Lidar HD de l’IGN"
author: "Josselin GIFFARD-CARLET"
date: "2023-10-11"
slug: "utilisation-des-donnees-lidar-hd-ign"
draft: true
categories: R
tags:
- lidar
- osm
---

## Initialisation

```{r}
# Clear existing objects from workspace and free memory
rm(list=ls(all=TRUE));gc()
```

# Charger les librairies

```{r message=FALSE, warning=FALSE}
library(lidR)
library(lidRviewer)
library(future) # require for dalponte2016 algorithm
# library(magrittr) # for the pipe %>%
library(ggplot2)
library(rgl) # require for 3d plotting
library(terra)
library(tidyterra)
library(dplyr)
library(tidyr)
#library(gridExtra) # for grid.arrange
library(leaflet)
library(sf)
library(osmdata)
library(tidyverse)
library(ggpubr)
```

```{r}
lasfile <- '~/Documents/geomatique/lidar/roi.copc.laz'
las_original <- readLAS(lasfile, select = "xyzic")
```

# Réduction de la densité du nuage de points

```{r}
las <- las_original %>% decimate_points(random(0.1)) # decimate points number
print(las)
```

```{r}
plot(las, size = 4, bg = "white", color = 'Classification')
rglwidget()
```
